src/Entity/Expositions.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ExpositionsRepository")
 */
class Expositions
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=200)
     */
    private $nom;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_debut;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_fin;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nb_vues;

    /**
     * @ORM\Column(type="text")
     */
    private $description_fr;

    /**
     * @ORM\Column(type="text")
     */
    private $description_en;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $ordre;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Users", inversedBy="exposition")
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Anonymes", mappedBy="exposition")
     */
    private $anonyme;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Oeuvres", inversedBy="exposition")
     */
    private $oeuvres;

    public function __construct()
    {
        $this->anonyme = new ArrayCollection();
        $this->oeuvres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getNbVues(): ?int
    {
        return $this->nb_vues;
    }

    public function setNbVues(?int $nb_vues): self
    {
        $this->nb_vues = $nb_vues;

        return $this;
    }

    public function getDescriptionFr(): ?string
    {
        return $this->description_fr;
    }

    public function setDescriptionFr(string $description_fr): self
    {
        $this->description_fr = $description_fr;

        return $this;
    }

    public function getDescriptionEn(): ?string
    {
        return $this->description_en;
    }

    public function setDescriptionEn(string $description_en): self
    {
        $this->description_en = $description_en;

        return $this;
    }

    public function getOrdre(): ?string
    {
        return $this->ordre;
    }

    public function setOrdre(?string $ordre): self
    { 
        $this->ordre = $ordre;

        return $this;
    }

    public function getUser(): ?Users
    {
        return $this->user;
    }

    public function setUser(?Users $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|anonymes[]
     */
    public function getAnonyme(): Collection
    {
        return $this->anonyme;
    }

    public function addAnonyme(anonymes $anonyme): self
    {
        if (!$this->anonyme->contains($anonyme)) {
            $this->anonyme[] = $anonyme;
            $anonyme->setExposition($this);
        }

        return $this;
    }

    public function removeAnonyme(anonymes $anonyme): self
    {
        if ($this->anonyme->contains($anonyme)) {
            $this->anonyme->removeElement($anonyme);
            // set the owning side to null (unless already changed)
            if ($anonyme->getExposition() === $this) {
                $anonyme->setExposition(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|oeuvres[]
     */
    public function getOeuvres(): Collection
    {
        return $this->oeuvres;
    }

    public function addOeuvre(oeuvres $oeuvre): self
    {
        if (!$this->oeuvres->contains($oeuvre)) {
            $this->oeuvres[] = $oeuvre;
        }

        return $this;
    }

    public function removeOeuvre(oeuvres $oeuvre): self
    {
        if ($this->oeuvres->contains($oeuvre)) {
            $this->oeuvres->removeElement($oeuvre);
        }

        return $this;
    }
}

src/Form/ExpositionsType.php
<?php

namespace App\Form;

use App\Entity\Oeuvres;
use App\Entity\Expositions;
use App\Entity\Artistes;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;

class ExpositionsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom', TextType::class, [
                'attr' => ['class' => 'form-control']
            ])
            ->add('date_debut', DateTimeType::class, [
                'attr' => ['class' => 'input-group']
            ])
            ->add('date_fin', DateTimeType::class, [
                'attr' => ['class' => 'input-group']
            ])
            ->add('description_fr', TextareaType::class, [
                'attr' => ['class' => 'form-control']
            ])
            ->add('description_en', TextareaType::class, [
                'attr' => ['class' => 'form-control']
            ])
            ->add('ordre', TextType::class, [
                'required' => false,
                'attr' => ['maxlength' => '5',
                'class' => 'form-control']
            ])
            ->add('oeuvres', EntityType::class, [
                'class' => Oeuvres::class,
                'choice_label' => 'titre',
                'multiple' => true,
                'expanded' => true
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Expositions::class,
            'entry_options' => [
                'attr' => ['class' => 'titre']
        ]]);
    }
}

src/Controller/ExpositionsController.php
<?php

namespace App\Controller;

use App\Entity\Expositions;
use App\Form\ExpositionsType;
use App\Repository\ExpositionsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/expositions")
 */
class ExpositionsController extends AbstractController
{
    /**
     * @Route("/", name="expositions_index", methods={"GET"})
     */
    public function index(ExpositionsRepository $expositionsRepository): Response
    {
        return $this->render('expositions/index.html.twig', [
            'expositions' => $expositionsRepository->findBy([],['id' => 'DESC']),
        ]);
    }

    /**
     * @Route("/new", name="expositions_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $exposition = new Expositions();
        $form = $this->createForm(ExpositionsType::class, $exposition);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $exposition->setUser($this->getUser());
            
            $entityManager = $this->getDoctrine()->getManager();

            $entityManager->persist($exposition);

            $entityManager->flush();

            return $this->redirectToRoute('expositions_index');
        }

        return $this->render('expositions/new.html.twig', [
            'exposition' => $exposition,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="expositions_show", methods={"GET"})
     */
    public function show(Expositions $exposition): Response
    {
        return $this->render('expositions/show.html.twig', [
            'exposition' => $exposition,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="expositions_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Expositions $exposition): Response
    {
        $form = $this->createForm(ExpositionsType::class, $exposition);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush(); 

            return $this->redirectToRoute('expositions_index', [
                'id' => $exposition->getId(),
            ]);
        }

        return $this->render('expositions/edit.html.twig', [
            'exposition' => $exposition,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="expositions_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Expositions $exposition): Response
    {
        if ($this->isCsrfTokenValid('delete'.$exposition->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($exposition);
            $entityManager->flush();
        }

        return $this->redirectToRoute('expositions_index');
    }
    
    /**
     * @Route("/generate/{id}", name="expositions_generate", methods={"GET"})
     */
    public function generate(Expositions $exposition): Response
    {
        return $this->render('expositions/generate.html.twig', [
            'exposition' => $exposition,
        ]);
    }
}

templates/expositions/_delete_form.html.twig
<form method="post" action="{{ path('expositions_delete', {'id': exposition.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ exposition.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/expositions/_form.html.twig
<ul>
{% for o in exposition.oeuvres %}
    <li>    
        <h5>Emplacement de {{ o.titre }} : {{ o.emplacement }}</h5>
    </li>
{% endfor %}
</ul>
{{ form_start(form) }}
    {{ form_widget(form) }}
    <div class="text-center my-3">
    <button class="btn btn-info">{{ button_label|default('Enregistrer') }}</button>
    </div>
{{ form_end(form) }}

templates/expositions/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification{% endblock %}

{% block body %}
{% include 'partials/_navbarGestion.html.twig' %}

<div class="container pt-5">
    <h1 class="script text-warning text-center">Modification</h1>
        <div class="text-center">
            <a class="btn btn-dark text-center mb-3" href="{{ path('expositions_index') }}">Retour</a>
        </div>


    {{ include('expositions/_form.html.twig', {'button_label': 'Update'}) }}

</div>
{% endblock %}

templates/expositions/generate.html.twig
{% extends 'base.html.twig' %}

{% block title %}Expositions qr codes{% endblock %}

{% block body %}
{% include 'partials/_navbarGestion.html.twig' %}
<div class="container pt-5">

    <div class="text-center text-warning script">
        <h2 class="pb-5"> {{exposition.nom}} </h2>
        <div class="text-center">
            <a class="btn btn-dark text-center mb-3" href="{{ path('expositions_index') }}">Retour</a>
        </div>
    </div>
 
    <div class="row">
   {% for oeuvre in exposition.oeuvres %}
    <div class="col-md-3">
        <div class="card text-center script">
            <p class="card-title">{{ oeuvre.titre }}<p>
            <img class="card-img" src="{{ asset('qr_codes/' ~ oeuvre.titre ~ oeuvre.id ~ '.png') }}"/>
        </div>
    </div>
    {% endfor %}
    </div>
</div>
{% endblock %}

templates/expositions/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Expositions{% endblock %}

{% block body %}

{% include 'partials/_navbarGestion.html.twig' %}
    <div class="container pt-5">

        <h1 class="script text-center text-warning pb-2">Expositions</h1>
        <div class="text-center">
            <a class="btn btn-dark text-center mb-3" href="{{ path('gestion') }}">Retour</a>
        </div>
        <table class="mx-auto table table-bordered ">
            <thead>
                <tr class="text-center">
                    <th scope="col">Nom</th>
                    <th scope="col">Date de Début</th>
                    <th scope="col">Date de Fin</th>
                    <th scope="col">Nombre de vues</th>
                    <th scope="col">Golden Path</th>
                    <th colspan="3"><a href="{{path('expositions_new')}}" class="btn btn-success">Nouvelle exposition</a></th>
                </tr>
            </thead>
            {% for exposition in expositions %}
            <tr class="text-center">
                <td>{{ exposition.nom|slice(0, 50) }}</td>
                <td>{{ exposition.dateDebut ? exposition.dateDebut|date('d m Y') : '' }}</td>
                <td>{{ exposition.dateFin ? exposition.dateFin|date('d m Y') : '' }}</td>
                <td>{{ exposition.nbVues }}</td>
                <td>{{ exposition.ordre }}</td>
                    <td><a href="{{ path('expositions_edit', {'id': exposition.id}) }}" class="btn btn-warning">Modifier</a></td>
                    <td><a href="{{ path('expositions_show', {'id': exposition.id}) }}" class="btn btn-info">Voir</a></td>
                    <td>{{ include('expositions/_delete_form.html.twig') }}</td>
            </tr>
                
            {% endfor %}
        </table>
    </div>
{% endblock %}

templates/expositions/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Expositions{% endblock %}

{% block body %}
{% include 'partials/_navbarGestion.html.twig' %}
<div class="container pt-5">
    <h1 class="text-center script text-warning">Nouvelle Expo</h1>
        <div class="text-center">
            <a class="btn btn-dark text-center mb-3" href="{{ path('expositions_index') }}">Retour</a>
        </div>
    {{ include('expositions/_form.html.twig') }}

</div>
{% endblock %}

templates/expositions/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Expositions{% endblock %}

{% block body %}

{% include 'partials/_navbarGestion.html.twig' %}
<div class="container pt-5">
    <h1 class="text-center script pb-5">{{ exposition.nom }}</h1>
        <div class="text-center">
            <a class="btn btn-dark text-center mb-3" href="{{ path('expositions_index') }}">Retour</a>
        </div>
    <div class="row">
        <div class="col-md-6 text-center py-5">
            <h3 class="script text-warning">Description Français</h3>
            <p class="pt-5">{{ exposition.descriptionFr }}</p>
        </div>
        <div class="col-md-6 text-center py-5">
            <h3 class="script text-warning">Description Anglais</h3>
            <p class="pt-5">{{ exposition.descriptionEn }}</p>
        </div>
    </div>
    <div class="row"> 
        <div class="col-md-12 py-5 text-center">
            <h2 class="script text-info ">Oeuvres dans l'exposition :</h2>
            <a class="btn btn-outline-info" href="{{ path('expositions_generate', {'id': exposition.id}) }}">Générer Qr Codes</a>
        </div>
    </div>
    <div class="row">   
        {% for o in exposition.oeuvres %}
            {% if o.type == 'Tableau' %}
                <div class="col-md-3 col-sm-12 p-3 d-flex align-items-stretch">
                    <div class="card">
                        <h1 class="card-title script text-center text-secondary">{{ o.titre }}</h1>
                        <img src="{{asset('uploads/media/')}}{{o.path}}" alt="oeuvre" class="card-img-top">
                            <div class="card-text text-center text-uppercase">
                                <p class="pt-2 m-0">Emplacement :</p>
                                <h1>{{ o.emplacement }}</h1>
                            </div>
                    </div>
                </div>
            {% elseif o.type == 'Musique' %}
                <div class="col-md-3 col-sm-12 p-3 d-flex align-items-stretch">
                    <div class="card">
                        <h1 class="card-title script text-center text-secondary">{{ o.titre }}</h1>
                        <img src="{{asset('img/music.png')}}" alt="Musique" class="card-img">
                        <div class="card-body">
                            <div>
                                <audio src="{{asset('uploads/media/')}}{{o.path}}" alt="oeuvre" controls>
                            </div>
                                <div class="card-text text-center text-uppercase">
                                    <p class="pt-2 m-0">Emplacement :</p>
                                    <h1>{{ o.emplacement }}</h1>
                                </div>
                        </div>
                    </div>
                </div>
            {% elseif o.type == 'Vidéo' %}
                <div class="col-md-3 col-sm-12 p-3 d-flex align-items-stretch">
                    <div class="card">
                        <h1 class="card-title script text-center text-secondary">{{ o.titre }}</h1>
                        <video controls src="{{asset('uploads/media/')}}{{o.path}}" alt="oeuvre" class="card-img-top"></video>
                            <div class="card-text text-center text-uppercase">
                                <p class="pt-2 m-0">Emplacement :</p>
                                <h1>{{ o.emplacement }}</h1>
                            </div>
                    </div>
                </div>
            {% endif %}
        {% else %}
            <div class="text-center">
                <p class="script">Aucune oeuvre dans l'exposition</p>
            </div> 
        {% endfor %}
    </div>
</div>
{% endblock %}