src/Entity/Artistes.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArtistesRepository")
 */
class Artistes
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $prenom;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $biographie_fr;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $biographie_en;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\oeuvres", mappedBy="artiste")
     */
    private $oeuvre;

    public function __construct()
    {
        $this->oeuvre = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getBiographieFr(): ?string
    {
        return $this->biographie_fr;
    }

    public function setBiographieFr(?string $biographie_fr): self
    {
        $this->biographie_fr = $biographie_fr;

        return $this;
    }

    public function getBiographieEn(): ?string
    {
        return $this->biographie_en;
    }

    public function setBiographieEn(?string $biographie_en): self
    {
        $this->biographie_en = $biographie_en;

        return $this;
    }

    /**
     * @return Collection|oeuvres[]
     */
    public function getOeuvre(): Collection
    {
        return $this->oeuvre;
    }

    public function addOeuvre(oeuvres $oeuvre): self
    {
        if (!$this->oeuvre->contains($oeuvre)) {
            $this->oeuvre[] = $oeuvre;
            $oeuvre->setArtistes($this);
        }

        return $this;
    }

    public function removeOeuvre(oeuvres $oeuvre): self
    {
        if ($this->oeuvre->contains($oeuvre)) {
            $this->oeuvre->removeElement($oeuvre);
            // set the owning side to null (unless already changed)
            if ($oeuvre->getArtistes() === $this) {
                $oeuvre->setArtistes(null);
            }
        }

        return $this;
    }
}

src/Form/ArtistesType.php
<?php

namespace App\Form;

use App\Entity\Artistes;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class ArtistesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom', TextType::class, [
                'attr' => ['class' => 'form-control']
            ])
            ->add('prenom', TextType::class, [
                'attr' => ['class' => 'form-control']
            ])
            ->add('biographie_fr', TextareaType::class, [
                'attr' => ['class' => 'form-control']
            ])
            ->add('biographie_en', TextareaType::class, [
                'attr' => ['class' => 'form-control']
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Artistes::class,
        ]);
    }
}

src/Controller/ArtistesController.php
<?php

namespace App\Controller;

use App\Entity\Artistes;
use App\Form\ArtistesType;
use App\Repository\ArtistesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/artistes")
 */
class ArtistesController extends AbstractController
{
    /**
     * @Route("/", name="artistes_index", methods={"GET"})
     */
    public function index(ArtistesRepository $artistesRepository): Response
    {
        return $this->render('artistes/index.html.twig', [
            'artistes' => $artistesRepository->findBy([],['nom' => 'ASC']),
        ]);
    }

    /**
     * @Route("/new", name="artistes_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $artiste = new Artistes();
        $form = $this->createForm(ArtistesType::class, $artiste);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($artiste);
            $entityManager->flush();

            return $this->redirectToRoute('artistes_index');
        }

        return $this->render('artistes/new.html.twig', [
            'artiste' => $artiste,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="artistes_show", methods={"GET"})
     */
    public function show(Artistes $artiste): Response
    {
        return $this->render('artistes/show.html.twig', [
            'artiste' => $artiste,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="artistes_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Artistes $artiste): Response
    {
        $form = $this->createForm(ArtistesType::class, $artiste);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('artistes_index', [
                'id' => $artiste->getId(),
            ]);
        }

        return $this->render('artistes/edit.html.twig', [
            'artiste' => $artiste,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="artistes_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Artistes $artiste): Response
    {
        if ($this->isCsrfTokenValid('delete'.$artiste->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($artiste);
            $entityManager->flush();
        }

        return $this->redirectToRoute('artistes_index');
    }
}

templates/artistes/_delete_form.html.twig
<form method="post" action="{{ path('artistes_delete', {'id': artiste.id}) }}" onsubmit="return confirm('Voulez-vous vrailent supprimer cet Artiste ?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ artiste.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/artistes/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <div class="text-center my-3">
    <button class="btn btn-info">{{ button_label|default('Enregistrer') }}</button>
    </div>
{{ form_end(form) }}

templates/artistes/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifications{% endblock %}

{% block body %}
{% include 'partials/_navbarGestion.html.twig' %}
<div class="container pt-5">
    <h1 class="text-center script text-warning">Modifications</h1>
        <div class="text-center">
            <a class="btn btn-dark text-center mb-3" href="{{ path('artistes_index') }}">Retour</a>
        </div>

    {{ include('artistes/_form.html.twig', {'button_label': 'Update'}) }}

</div>
{% endblock %}

templates/artistes/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Artistes{% endblock %}

{% block body %}
    {% include 'partials/_navbarGestion.html.twig' %}
    <div class="container pt-5">

        <h1 class="script text-center text-warning">Artistes</h1>
        <div class="text-center">
            <a class="btn btn-dark text-center mb-3" href="{{ path('gestion') }}">Retour</a>
        </div>
        <table class="mx-auto table table-bordered ">
            <thead>
                <tr class="text-center">
                    <th scope="col">Nom</th>
                    <th scope="col">Prénom</th>
                    <th scope="col">Biographie Anglais</th>
                    <th scope="col">Biographie Français</th>
                    <th colspan="2"><a href="{{path('artistes_new')}}" class="btn btn-info">Ajouter un Artiste</a></th>
                </tr>
            </thead>
            {% for artiste in artistes %}
            <tr class="text-center">
                <td>{{ artiste.nom|slice(0, 50) }}</td>
                <td>{{ artiste.prenom|slice(0, 50) }}</td>
                <td>{{ artiste.biographieEn|slice(0, 50) }}</td>
                <td>{{ artiste.biographieFr|slice(0, 50)}}</td>
                    <td><a href="{{ path('artistes_edit', {'id': artiste.id}) }}" class="btn btn-warning">Modifier</a></td>
                    <td>{{ include('artistes/_delete_form.html.twig') }}</td>
            </tr>   
            {% endfor %}
{% endblock %}

templates/artistes/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Artistes{% endblock %}

{% block body %}
{% include 'partials/_navbarGestion.html.twig' %}
<div class="container pt-5">
        <h1 class="text-center script text-warning">Ajouter un artiste</h1>
        <div class="text-center">
            <a class="btn btn-dark text-center mb-3" href="{{ path('artistes_index') }}">Retour</a>
        </div>

    {{ include('artistes/_form.html.twig') }}

</div>
{% endblock %}

templates/artistes/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Artistes{% endblock %}

{% block body %}
    <h1>Artistes</h1>
        <div class="text-center">
            <a class="btn btn-dark text-center mb-3" href="{{ path('artistes_index') }}">Retour</a>
        </div>
    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ artiste.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ artiste.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ artiste.prenom }}</td>
            </tr>
            <tr>
                <th>Biographie_fr</th>
                <td>{{ artiste.biographieFr }}</td>
            </tr>
            <tr>
                <th>Biographie_en</th>
                <td>{{ artiste.biographieEn }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('artistes_index') }}">back to list</a>

    <a href="{{ path('artistes_edit', {'id': artiste.id}) }}">edit</a>

    {{ include('artistes/_delete_form.html.twig') }}
{% endblock %}